### ISSUE TITLE
missing centos-cloudify-cli.sh script

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOOrchestrator-CLI#1]
Hi, 
trying to build docker image fails with the following error:
```
ADD failed: stat /var/lib/docker/tmp/docker-builder464712798/centos-cloudify-cli.sh: no such file or directory
```
centos script is actually missing!

**Comment by emepetres** [comment]
You can also use directly the image from https://hub.docker.com/u/mso4sc/dashboard/
